import { createServerFn } from "@tanstack/react-start";

/**
 * Email actions — sends transactional/outreach email through Resend
 * from the verified domain (hello@getscoutai.app).
 *
 * This replaces the platform inbox for outreach so we don't hit bounce
 * thresholds on the platform's built-in email.
 */

export interface SendOutreachEmailInput {
  to: string;
  subject: string;
  body: string;
}

export interface SendOutreachEmailResult {
  success: boolean;
  error?: string;
  emailId?: string;
}

/**
 * Core implementation: send a plain-text email via Resend.
 * Errors are caught and returned — never thrown — so callers (and the
 * web UI) can surface them without crashing the request.
 */
async function sendEmailImpl(data: SendOutreachEmailInput): Promise<SendOutreachEmailResult> {
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    return { success: false, error: "RESEND_API_KEY is not set — connect a Resend API key before sending email." };
  }
  try {
    const { Resend } = await import("resend");
    const resend = new Resend(apiKey);
    const fromAddress = process.env.RESEND_EMAIL_FROM || "hello@getscoutai.app";
    const result = await resend.emails.send({
      from: `Scout AI <${fromAddress}>`,
      to: [data.to],
      subject: data.subject,
      text: data.body,
    });
    if (result.error) {
      return { success: false, error: result.error.message };
    }
    return { success: true, emailId: result.data?.id };
  } catch (err: unknown) {
    return {
      success: false,
      error: err instanceof Error ? err.message : "Failed to send email via Resend",
    };
  }
}

/**
 * TanStack Start server function. In the compiled app this is invoked by
 * the client through RPC (and directly on the server within a request
 * context); see the exported `sendOutreachEmail` wrapper below.
 */
const sendOutreachEmailFn = createServerFn({ method: "POST" })
  .validator((input: unknown) => {
    if (typeof input !== "object" || input === null) throw new Error("Invalid input");
    const { to, subject, body } = input as Record<string, unknown>;
    if (typeof to !== "string" || !to.trim()) throw new Error("Recipient email is required");
    if (typeof subject !== "string" || !subject.trim()) throw new Error("Subject is required");
    if (typeof body !== "string" || !body.trim()) throw new Error("Body is required");
    return { to: to.trim(), subject: subject.trim(), body: body.trim() } satisfies SendOutreachEmailInput;
  })
  .handler(async ({ data }: { data: SendOutreachEmailInput }): Promise<SendOutreachEmailResult> => {
    return sendEmailImpl(data);
  });

/**
 * Exported entry point — usable from the app (RPC / server context) and
 * from standalone scripts and tests.
 *
 * - Browser (client bundle): `sendOutreachEmailFn` is the RPC stub
 *   generated by the TanStack plugin, so we call it directly.
 * - Server inside a request: a Start context exists, so the server fn runs
 *   its real handler (which the compiled build wires through `__executeServer`).
 * - Standalone (bun scripts / tests, no Start context): run the
 *   implementation directly, since the framework middleware chain requires
 *   a request context it only has in the compiled server runtime.
 */
export async function sendOutreachEmail(opts: { data: SendOutreachEmailInput }): Promise<SendOutreachEmailResult> {
  if (typeof window !== "undefined") {
    return sendOutreachEmailFn(opts);
  }
  const { getStartContext } = await import("@tanstack/start-storage-context");
  if (getStartContext({ throwIfNotFound: false })) {
    return sendOutreachEmailFn(opts);
  }
  return sendEmailImpl(opts.data);
}
